apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-docker-container-test
  name: nodejs-docker-container-test
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nodejs-docker-container-test
  template:
    metadata:
      labels:
        deployment: nodejs-docker-container-test
    spec:
      containers:
        - image: $(params.IMAGE_NAME)
          imagePullPolicy: Always
          name: nodejs-docker-container-test
          ports:
            - containerPort: 3000
              protocol: TCP