apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $(params.APP_NAME)
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: $(params.APP_NAME)
  template:
    metadata:
      labels:
        deployment: $(params.APP_NAME)
    spec:
      containers:
        - image: $(params.IMAGE_NAME)
          imagePullPolicy: Always
          name: $(params.APP_NAME)
          ports:
            - containerPort: 3000
              protocol: TCP