apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-docker-container-test
  name: nodejs-docker-container-test
spec:
  type: ClusterIP
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    deployment: nodejs-docker-container-test